name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g clean-css-cli terser

      - name: Prepare dist structure
        run: |
          mkdir -p dist/public/css
          mkdir -p dist/public/images
          mkdir -p dist/assets/js

      - name: Copy static files
        run: |
          cp index.html dist/
          cp public/favicon.ico dist/
          cp -r public/images/* dist/public/images/

      - name: Minify and bundle JavaScript
        run: |
          cat src/*.js src/helpers/*.js > dist/assets/js/bundle.js
          terser dist/assets/js/bundle.js -c -m -o dist/assets/js/bundle.min.js
          rm dist/assets/js/bundle.js

      - name: Minify CSS
        run: |
          cleancss public/css/styles.css -o dist/public/css/styles.min.css

      - name: Update HTML references
        run: |
          sed -i 's/public\/css\/styles.css/public\/css\/styles.min.css/' dist/index.html
          sed -i 's/src\/main.js/assets\/js\/bundle.min.js/' dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist