name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install -g clean-css-cli terser

      - name: Build and Minify
        run: |
          mkdir -p dist/assets/js
          mkdir -p dist/assets/css
          cp index.html dist/
          cp -r public/images dist/images
          cp public/favicon.ico dist/
      
          # Concatenar todos los JS en uno solo temporalmente
          cat src/**/*.js > dist/assets/js/all.js
      
          # Minificar el archivo concatenado
          npx terser dist/assets/js/all.js -c -m -o dist/assets/js/main.min.js
      
          # Borrar archivo temporal
          rm dist/assets/js/all.js
      
          # Minificar CSS
          npx cleancss -o dist/public/css/styles.min.css public/css/styles.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
